services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tienda
      MYSQL_USER: Max
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"